# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sG0kHuowPHeoWwidLAl__VJApE6r4Fuz
"""

import pandas as pd
import requests
from PIL import Image
import io
import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import hashlib

def download_satellite_image(lat, lon, house_id, mapbox_token, output_dir):
    """Download single satellite image"""
    url = f"https://api.mapbox.com/styles/v1/mapbox/satellite-v9/static/{lon},{lat},18/512x512@2x?access_token={mapbox_token}"

    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        img = Image.open(io.BytesIO(response.content))
        filename = f"{house_id}_{lat:.6f}_{lon:.6f}.jpg"
        filepath = os.path.join(output_dir, filename)
        img.save(filepath, 'JPEG', quality=95)

        return house_id, filepath
    except Exception as e:
        print(f"Failed {house_id}: {e}")
        return house_id, None

def bulk_download_satellite_images(csv_path, mapbox_token, output_dir='satellite_images', max_workers=10):
    """Download satellite images for all houses"""
    os.makedirs(output_dir, exist_ok=True)

    df = pd.read_csv(csv_path)
    print(f"Downloading {len(df)} satellite images...")

    successful = 0
    failed = []

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(download_satellite_image, row['lat'], row['long'],
                          row['id'], mapbox_token, output_dir): row['id']
            for _, row in df.iterrows()
        }

        for future in as_completed(futures):
            house_id, result = future.result()
            if result:
                successful += 1
            else:
                failed.append(house_id)
            time.sleep(0.1)  # Rate limit

    print(f"✅ Success: {successful}/{len(df)}")
    print(f"❌ Failed: {len(failed)} IDs: {failed[:10]}...")


    summary = pd.DataFrame({
        'house_id': df['id'],
        'image_path': [f"satellite_images/{id_}_*.jpg" for id_ in df['id']]
    })
    summary.to_csv('image_download_summary.csv', index=False)

    return summary

# Usage
MAPBOX_TOKEN = "pk.eyJ1IjoibWFuZ2VzaDExMTExIiwiYSI6ImNtanBramluajA3ZTIzZXF4ZzFvZ294Y3EifQ.A6oaJAqIVXDe9v2UvRq2kQ"

# Download ALL 16K images (batch to avoid rate limits)
summary = bulk_download_satellite_images(
    '/content/train(1)(train(1)).csv',
    MAPBOX_TOKEN,
    max_workers=5
)

